# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [ ]:
import numpy as np

2. Create a null vector of size 10 

In [ ]:
nullvector  = np.zeros(10)
nullvector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [ ]:
vector = np.arange(10,49)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [ ]:
array_shape = vector.shape
array_shape

(39,)

5. Print the type of the previous array in question 3

In [ ]:
print(vector.dtype)

int64


6. Print the numpy version and the configuration


In [ ]:
print(np.version.version)
print(np.show_config())

1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [ ]:
vector.ndim

1

8. Create a boolean array with all the True values

In [ ]:
boolean = np.ones(10,dtype=bool)

boolean

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [ ]:
two_dimension = np.zeros((2,9))
two_dimension

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

10. Create a three dimensional array



In [ ]:
three_dimension = np.zeros((3,9))
three_dimension

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [ ]:
orignal = np.arange(10)
reverse = np.flip(orignal)

print('Orignal',orignal)
print('Reverse',reverse)

Orignal [0 1 2 3 4 5 6 7 8 9]
Reverse [9 8 7 6 5 4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [ ]:
vector_10 = np.zeros(10)
print('Orignal',vector_10)
vector_10[4] = 1
print('fifth',vector_10)

Orignal [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
fifth [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [ ]:
matrix = np.zeros((3,3))
matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype('float64')
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [ ]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

print(np.multiply(arr1,arr2))

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [ ]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
compare = (arr1 == arr2).all()
print(compare)


False


17. Extract all odd numbers from arr with values(0-9)

In [ ]:
arr = np.arange(10)

print(arr[arr %2==1])

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [ ]:
 arr[arr %2==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [ ]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [ ]:
arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [ ]:
arr2d = np.array([
            [1, 2, 3],

            [4, 5, 6], 
 
            [7, 8, 9]
            ])
arr2d[1,1] =12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [ ]:
arr3d = np.array([[
                   [1, 2, 3], 
                   [4, 5, 6]], 
                  [[7, 8, 9], 
                   [10, 11, 12]
                   ]])
arr3d[0,0] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [ ]:
arr = np.arange(10).reshape((2,5))
arr[0:1]


array([[0, 1, 2, 3, 4]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [ ]:
arr = np.arange(10).reshape((2,5))
arr[1:]

array([[5, 6, 7, 8, 9]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [ ]:
arr = np.arange(10).reshape((2,5))
arr[0:1,0:2]

array([[0, 1]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
arr = np.random.random((10,10))
print("minimum",arr.min())
print("maximum",arr.max())

minimum 0.021259597411152464
maximum 0.992002128170114


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.searchsorted(a, np.intersect1d(a, b))


array([1, 5])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(data[names != 'Will'])

[[ 0.84432853  0.53067604 -1.68839499  1.03327902]
 [-1.20129652 -0.22640867  0.41800438 -0.0735006 ]
 [ 0.80575727 -0.87400824 -1.17074196 -0.82106682]
 [ 0.0919583   1.56430332 -1.02905693  2.63033522]
 [ 1.62897172 -0.06137463  0.18308903  0.8211775 ]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(data[(names != 'Will') & (names!= 'Joe')])

[[-0.14808279  0.18640191  1.35910404 -2.03975106]
 [-0.36658318 -1.8730794  -1.06400276 -0.38177495]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [ ]:
rand_arr = np.random.uniform(1,15, size=(5,3))
print(rand_arr)

[[-0.13831625  1.3384155   0.02965972  0.36343315]
 [-0.25119592  1.70716894  0.39602581  0.26230761]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [ ]:
rand_arr2 = np.random.uniform(1,16, size=(2,2,4))
print(rand_arr2)

[[[ 8.14197317  9.31739042  9.01947455 11.07276158]
  [ 8.64598575 10.3286936   1.01231646 15.29842937]]

 [[ 8.03355781 14.52663716 15.21604014  6.62241771]
  [ 4.24080101 10.59637978  5.27219778 13.96741518]]]


33. Swap axes of the array you created in Question 32

In [ ]:
print("Original Array")
print(rand_arr2)
print("Swapped Axes")
print(np.swapaxes(rand_arr2, 2, 0))

Original Array
[[[ 8.14197317  9.31739042  9.01947455 11.07276158]
  [ 8.64598575 10.3286936   1.01231646 15.29842937]]

 [[ 8.03355781 14.52663716 15.21604014  6.62241771]
  [ 4.24080101 10.59637978  5.27219778 13.96741518]]]
Swapped Axes
[[[ 8.14197317  8.03355781]
  [ 8.64598575  4.24080101]]

 [[ 9.31739042 14.52663716]
  [10.3286936  10.59637978]]

 [[ 9.01947455 15.21604014]
  [ 1.01231646  5.27219778]]

 [[11.07276158  6.62241771]
  [15.29842937 13.96741518]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [ ]:
arr = np.random.uniform(0,20, size=(10))
arr = arr.astype('int32') 
arr =np.sqrt(arr)
arr = np.where(arr < 0.5, 0, arr)
arr = arr.astype('int32')
print(arr)

[3 3 2 3 1 2 3 3 3 2]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [ ]:
arr = np.random.uniform(0,20, size=(10))
arr1 = np.random.uniform(0,20, size=(10))
newArr = np.maximum(arr,arr1)
print(f"Array 1 : {arr}")
print(f"Array 2 : {arr1}")
print(f"New Array : {newArr}")

Array 1 : [17.11078159 18.57107253  4.55402316  3.88869613 17.50918421 12.40961257
 18.79457758  3.71854873 17.6108822   1.10887048]
Array 2 : [ 1.01551459 19.02930045  0.42004248  8.22193384  1.59944791  0.48751607
  9.23570084  4.79681869  1.01496363 10.29993723]
New Array : [17.11078159 19.02930045  4.55402316  8.22193384 17.50918421 12.40961257
 18.79457758  4.79681869 17.6108822  10.29993723]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.sort(np.unique(names)))

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [ ]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a, b)
print(c)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [ ]:
sampleArray = np.array([
    [34,43,73],
    [82,22,12],
    [53,94,66]
])
newColumn = np.array([[10,10,10]])
sampleArray = np.delete(sampleArray, 2, axis=1)
sampleArray = np.insert(sampleArray, 2, newColumn, axis=1)
print(sampleArray)

[[34 43 10]
 [82 22 10]
 [53 94 10]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(np.dot(x,y))

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [ ]:
arr = np.random.uniform(1,20,size=(4,5))
arr = arr.astype('int32')
print(arr.cumsum())


[ 18  32  46  60  65  83  84  93 112 131 150 169 173 191 199 200 216 233
 234 242]
