# Numpy_Assignment_2::

## Question:1

In [ ]:
import numpy as np


### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
d1 = np.arange(10)
d2 = d1.reshape(2,5)
print('1D Array',d1)
print('2D Array',d2)

1D Array [0 1 2 3 4 5 6 7 8 9]
2D Array [[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
 x = np.arange(10)
 y = np.arange(10)

 np.vstack((x,y))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [ ]:
 x = np.arange(10)
 y = np.arange(10)

 np.hstack((x,y))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
multi_array = np.random.rand(5,2,3)
flaten = multi_array.flatten()
print('ND Array',multi_array)
print('1D Array',flaten)

ND Array [[[0.729691   0.18751883 0.61097214]
  [0.20281557 0.23571699 0.76151339]]

 [[0.24042522 0.52842129 0.17126728]
  [0.5842863  0.06018962 0.45089436]]

 [[0.14261655 0.35930091 0.75480573]
  [0.56476562 0.18397486 0.13763462]]

 [[0.86434918 0.18247911 0.75072109]
  [0.51702574 0.98150235 0.7519133 ]]

 [[0.08600708 0.27541689 0.87975586]
  [0.00127755 0.5864263  0.79720186]]]
1D Array [0.729691   0.18751883 0.61097214 0.20281557 0.23571699 0.76151339
 0.24042522 0.52842129 0.17126728 0.5842863  0.06018962 0.45089436
 0.14261655 0.35930091 0.75480573 0.56476562 0.18397486 0.13763462
 0.86434918 0.18247911 0.75072109 0.51702574 0.98150235 0.7519133
 0.08600708 0.27541689 0.87975586 0.00127755 0.5864263  0.79720186]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [ ]:
arr5 = np.array([
    [ 0, 1, 2],
    [ 3, 4, 5],
    [ 6, 7, 8],
    [ 9, 10, 11],
    [12, 13, 14]
])
arr5 = np.ravel(arr5)
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

array([[ 0, 1, 2],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])

In [ ]:
arr5.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [ ]:
arr6 = np.random.randint(1,25, size = (5,5))
print("Original Array: \n")
print (arr6)
print("\n")
print("Square of Array: \n")
print(arr6 ** 2)

Original Array: 

[[ 2  1 17 19  5]
 [24 22 20 19  3]
 [16 23 12  7  1]
 [ 4  1  3 14  2]
 [10  1  2 23 20]]


Square of Array: 

[[  4   1 289 361  25]
 [576 484 400 361   9]
 [256 529 144  49   1]
 [ 16   1   9 196   4]
 [100   1   4 529 400]]


## Question:8

### Create 5x6 an array and find the mean?

In [ ]:
arr8 = np.random.randint(1,20, size = (5,6))
print("Original Array: \n")
print (arr8)
print("\n")
print("Mean of Array: \n")
print(arr8.mean())

Original Array: 

[[13  6  1  7 15 16]
 [ 9  4  9  2  6 15]
 [ 4  7 15  6  1  4]
 [10  1 18 17  1 12]
 [ 2 10  9  2 15  3]]


Mean of Array: 

8.0


## Question:9

### Find the standard deviation of the previous array in Q8?

In [ ]:
print("Original Array: \n")
print (arr8)
print("\n")
print("Standard deviation of Array: \n")
print(np.std(arr8))

Original Array: 

[[13  6  1  7 15 16]
 [ 9  4  9  2  6 15]
 [ 4  7 15  6  1  4]
 [10  1 18 17  1 12]
 [ 2 10  9  2 15  3]]


Standard deviation of Array: 

5.428320796219275


## Question:10

### Find the median of the previous array in Q8?

In [ ]:
print("Original Array: \n")
print (arr8)
print("\n")
print("Median of Array: \n")
print(np.median(arr8))

Original Array: 

[[13  6  1  7 15 16]
 [ 9  4  9  2  6 15]
 [ 4  7 15  6  1  4]
 [10  1 18 17  1 12]
 [ 2 10  9  2 15  3]]


Median of Array: 

7.0


## Question:11

### Find the transpose of the previous array in Q8?

In [ ]:
print("Original Array: \n")
print (arr8)
print("\n")
print("Transpose of Array: \n")
print(np.transpose(arr8))

Original Array: 

[[13  6  1  7 15 16]
 [ 9  4  9  2  6 15]
 [ 4  7 15  6  1  4]
 [10  1 18 17  1 12]
 [ 2 10  9  2 15  3]]


Transpose of Array: 

[[13  9  4 10  2]
 [ 6  4  7  1 10]
 [ 1  9 15 18  9]
 [ 7  2  6 17  2]
 [15  6  1  1 15]
 [16 15  4 12  3]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [ ]:
arr7 = np.random.randint(1,20, size = (4,4))
print("Original Array: \n")
print (arr7)
print("\n")
print("Sum of diagonal elements of Array: \n")
print(np.trace(arr7))

Original Array: 

[[ 3 14 14  4]
 [ 7 12  2 14]
 [ 4  9  9  6]
 [14  8  5 15]]


Sum of diagonal elements of Array: 

39


## Question:13

### Find the determinant of the previous array in Q12?

In [ ]:
print("Original Array: \n")
print (arr7)
print("\n")
print("Determinant of Array: \n")
print(np.linalg.det(arr7))

Original Array: 

[[ 3 14 14  4]
 [ 7 12  2 14]
 [ 4  9  9  6]
 [14  8  5 15]]


Determinant of Array: 

2491.999999999998


## Question:14

### Find the 5th and 95th percentile of an array?

In [ ]:
print("Original Array: \n")
print (arr7)
print("\n")
print(f"5th percentile of array: {np.percentile(arr7, 5)}")
print(f"95th percentile of array: {np.percentile(arr7, 95)}")

Original Array: 

[[ 3 14 14  4]
 [ 7 12  2 14]
 [ 4  9  9  6]
 [14  8  5 15]]


5th percentile of array: 2.75
95th percentile of array: 14.25


## Question:15

### How to find if a given array has any null values?

In [ ]:
np.isnan(arr7).any()

False